### ISSUE TITLE
Configure dependabot

### ISSUE THREAD

**Issue by zambrovski** [xmolecules/jmolecules-integrations#115]
As a developer I want to use latest versions of libraries, especially if these are on provided scope. Dependabot is taking care of dependency updates and automatically create PRs for the repository.

Current SpringBoot version is for example 2.7.0 and jmolecules 1.5.0.

**Comment by odrotbohm** [comment]
I've so far experienced Dependabot more a distraction than actually helpful, as it doesn't necessarily know about the version upgrade policies of individual branches. The Boot version is a good example. We still depend on 2.6 as we do not want to force users onto 2.7 as the release has not been out for too long. Of course, if we upgraded, they could potentially downgrade to 2.6 explicitly, but I think it's nicer to just refer to a more stable version OOTB and allow users to seamlessly use Boot 2.7 if they have their projects configured to it.

What problem in particular were you thinking of that using Dependabot would solve?

**Comment by zambrovski** [comment]
I'm fine with doing it manually, just noticed that jmolecules-integration is not using the latest released jmolecules...

**Comment by odrotbohm** [comment]
It's a similar situation as described above: there's no need to depend on the latest version of the API, yet. Thus, we don't want to force folks onto the new API version yet. Have a look at the [`jmolecules-bom`](https://github.com/xmolecules/jmolecules-bom) project that provides dedicated versions that combine various compatible flavors of both API and integrations.
