### ISSUE TITLE
Provide ByteBuddy plugin for Axon Framework

### ISSUE THREAD

**Issue by zambrovski** [xmolecules/jmolecules-integrations#121]
In a typical Axon Framework project I want to use the jmolecules annotations instead of Axon annotation.

**Acceptance Criteria**

Get rid of the following annotations:

- Command / Command Model: `@TargetAggregateIdentifier`, `@AggregateIdentifier`, `@Aggregate`, `@AggregateRoot`, `@EventSouringHandler`
- Event Handler: `@EventHandler`

**Currently out of scope**

* Query Model: `@Query`, `@QueryHandler`, because currently not supported by jmolecules (no annotations yet, see https://github.com/xmolecules/jmolecules/issues/87)

* Event: @Revision (not support inside of `@DomainEvent` see https://github.com/xmolecules/jmolecules/issues/84)

**Comment by odrotbohm** [comment]
I have just pushed your commit and some polishing on top to the `feature/121-axon` branch. It uses the slightly reworked `@Association` annotation already merged into the jMolecules API library. Please have a final quick glance before I merge it into `main`. I've pulled out the example into the `jmolecules-examples` repository (all here locally, builds fine this feature branch work here included and about to be merged as well in case we think we're done here for now).

Sorry for the hassle, I'll have to review the code formatting settings going forward.

**Comment by zambrovski** [comment]
Looks good! Thank you for taking time and finishing it. 
Sorry I could not help you with formatting, but somehow the formatter application changes the source code from develop...

**Comment by zambrovski** [comment]
For the examples - great. As soon the integration is merged, I can also provide the Axon example in Kotlin, since this is in my opinion a much better match for creation of DDD CARS/ES systems using Axon Framework than Java.

**Comment by odrotbohm** [comment]
That's in place now. Happy to see the Kotlin based Axon example. Thanks again!
