### ISSUE TITLE
Slight version mismatch between Maven Central and Github

### ISSUE THREAD

**Issue by zambrovski** [xmolecules/jmolecules-integrations#131]
Hi,

latest release announced on github is called 0.11

![image](https://user-images.githubusercontent.com/673128/177627499-dfdb16fe-4652-4a58-ba92-d59b55966243.png)

released on June 21.

On Maven Central, the latest version is 1.6.0 released on June 21.

![image](https://user-images.githubusercontent.com/673128/177627709-bebbf5ed-bb2d-4c42-ad87-33477a26a690.png)

I believe it is the same version, please rename the name of the github accordingly.

**Comment by odrotbohm** [comment]
1.6.0 was released by accident (as we were releasing jMolecules 1.6 that very same day). Unfortunately, artifacts cannot be removed from Maven central, which means we cannot do anything about that.
