### ISSUE TITLE
Priortize constructors over factory methods in converters

### ISSUE THREAD

**Issue by ooraini** [xmolecules/jmolecules-integrations#191]
The following [line](https://github.com/xmolecules/jmolecules-integrations/blob/5cec533da7027f8e47a291ecd31c2eff75a985ec/jmolecules-spring/src/main/java/org/jmolecules/spring/PrimitivesToIdentifierConverter.java#L134):
```
return creatorMethod.isPresent() ? creatorMethod : detectConstructor(target, source);
```

selects the factory method `of` if it's present over the constructor. Seems harmless until you you have a hierarchy of classes/interfaces in which some of them define the method `of`. I was surprised when I got `ClassCastException`  because the factory method in the super interface returned an instance of a different type:

```
interface Super {
  static Super of(String s) {
    // return either new A, or new B
  }
}

record A(String s) implements Super {}
record B(String s) implements Super {}
```

Is it more sensible to prefer the constructor when present over the factory method? The constructor is guaranteed to return an instance of the same type.

**Comment by odrotbohm** [comment]
Good catch! I've revised the lookup to only consider the actual target class so that it'd naturally fall back to the concrete class' constructor.
