### ISSUE TITLE
ByteBuddy persistence mapping generation not working with Kotlin

### ISSUE THREAD

**Issue by odrotbohm** [xmolecules/jmolecules-integrations#199]
### Discussed in https://github.com/xmolecules/jmolecules/discussions/106

<div type='discussions-op-text'>

<sup>Originally posted by **Alfhir** November  8, 2023</sup>
Hello,
I am trying Spring Boot Modulith and jMolecules in a Kotlin project. I suspect that Bytebuddy is not doing it's magic and I don't know how to debug this. If someone could have a look at my config and help, that would be really nice!

build.gradle.kts
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath(platform("org.jmolecules:jmolecules-bom:2021.1.0"))
		classpath("org.jmolecules.integrations:jmolecules-bytebuddy")
	}
}

plugins {
	id("org.springframework.boot") version "3.1.5"
	id("io.spring.dependency-management") version "1.1.3"
	id("net.bytebuddy.byte-buddy-gradle-plugin") version "1.14.9"
	kotlin("jvm") version "1.8.22"
	kotlin("plugin.spring") version "1.8.22"
	kotlin("plugin.jpa") version "1.8.22"
}

byteBuddy {
	transformation{
		plugin = org.jmolecules.bytebuddy.JMoleculesPlugin::class.java
	}
}

group = "com.example.demo"
version = "0.0.1-SNAPSHOT"

java {
	sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
	mavenCentral()
}

dependencies {
        // omitted some dependencies for brevity
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.springframework.modulith:spring-modulith-starter-jpa") // includes core

	implementation(platform("org.jmolecules:jmolecules-bom:2021.1.0"))
	implementation("org.jmolecules:kmolecules-ddd:1.9.0")
	implementation("org.jmolecules:jmolecules-events")
	implementation("org.jmolecules.integrations:jmolecules-spring")
	implementation("org.jmolecules.integrations:jmolecules-jpa")
	compileOnly("org.jmolecules.integrations:jmolecules-bytebuddy")
	runtimeOnly("org.postgresql:postgresql")
}

dependencyManagement {
	imports {
		mavenBom("org.springframework.modulith:spring-modulith-bom:1.0.2")
	}
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs += "-Xjsr305=strict"
		jvmTarget = "17"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}
```

and here's some code from the classes, I am trying to persist (all in internal package but the repo):
```
@org.jmolecules.ddd.annotation.Repository
interface Dungeons: CrudRepository<Dungeon, DungeonIdentifier>

@JvmInline
value class DungeonIdentifier(val id: UUID = UUID.randomUUID()): Identifier {
    fun of(id: UUID)  = DungeonIdentifier(id)
}

@Table(name = "dungeon")
data class Dungeon(
    override val id: DungeonIdentifier = DungeonIdentifier(),
) : AggregateRoot<Dungeon, DungeonIdentifier>
```

I get 
> Found 0 JPA repository interfaces.

and 

> Could not safely identify store assignment for repository candidate interface com.example.demo.dungeon.Dungeons; If you want this repository to be a JPA repository, consider annotating your entities 

So that's why I suspect they're not being annotated w. the necessary JPA annotations.

What am I overseeing?

</div>

**Comment by odrotbohm** [comment]
Would you mind packaging this up as a minimal buildable project? I am not a Kotlin expert but in [the tickets we've got so far](https://github.com/xmolecules/jmolecules-integrations/issues/196), the primary problem was that the project did not set up Kotlin compilation in a way that the generated class files could be found in places that standard java tooling expects them to end up`

**Comment by Alfhir** [comment]
Thanks for getting back at me so fast! I'll make a minimal buildable project asap and post the URL here.

**Comment by Alfhir** [comment]
I've set up a [minmal branch](https://github.com/Alfhir/thing/tree/minimal-buildable), is that sufficient?

**Comment by odrotbohm** [comment]
I think the core of the issue is indeed that ByteBuddy is inspecting the standard Java compiler target folder, not the Kotlin one. Traces of that can be found here:

* https://github.com/raphw/byte-buddy/issues/1284
* https://github.com/xmolecules/jmolecules-examples/issues/6

I'm sorry I don't have better news.

**Comment by Alfhir** [comment]
Thank you very much for investigating. I'll use Java then or see if I can come up with a custom ByteBuddyTask.

**Comment by odrotbohm** [comment]
I strongly assume that any contribution making this more usable from within Gradle would be welcome by Raphael. We're just neither Gradle nor Kotlin experts.
