### ISSUE TITLE
Separate definitions of architecture styles (API) from utility methods to collect this information from code

### ISSUE THREAD

**Issue by zambrovski** [xmolecules/jmolecules-integrations#200]
Hi Oliver,

I love JMolecule-ArchUnit integration and would like to use it in Kotlin projects too. The problem is - there is no Kotlin construct for `package.java` package marker. 

As a result, you need to annotate every class with corresponding JMolecules annotation. 
Especially if I want to mark the entire package as Infrastructure Ring or Application Ring it becomes very boring...

I was thinking how to achieve this and came to a possible solution of putting a marker file into the package / folder and mark it there. Looking at the code, I realized that the definition of `hexagonal`, `onion`,  etc architectures is tightly coupled with the way you detect, that a particular class belongs to the certain layer.

Would you accept a proposal / PR to separate this things, without changing it for the user, but allowing other implementations to hook into the detection?

What do you think?

Cheers,

Simon

**Comment by odrotbohm** [comment]
I'm not sure we can fix Kotlin here. The concept of annotating packages is simply not a thing in it and if you care about this, I think you need to make your voice heard in the Kotlin bug tracker. One workaround I've seen was to simpliy declare the `package-info.java` as Java file and let the Java compiler compile that file.

Regarding the pluggability of the definition it feels like we're getting close to formulating the ArchUnit rules explicitly. The point of jMolecules is not having to do that in the first place. I assume you'd like some callback to be able to identify the package containing a layer / ring, like a `BiPredicate<JavaPackage, Class<? extends Annotation>`?

**Comment by zambrovski** [comment]
Hi Oliver,

I just created a separate repository for now and could implement a "Marker class approach" in it. That is if you put a marker type into a package, you could use that for annotation of the entire package.

Check here please: https://github.com/toolisticon/jmolecules-archunit-kotlin

I still believe it is a good idea to have the predicates independent from the definitions of the architectures.

Cheers,

Simon

**Comment by odrotbohm** [comment]
I have a prototyp here that would allow you to write something like this:

```java
JMoleculesArchitectureRules.ensureLayering(StereotypeLookup.onMarkerType("Foo"));
```

This would, for each class considered try to find the marker type the class' package or parent packages and consider that type's annotation for assignment.

**Comment by zambrovski** [comment]
Hi Oliver,

This is exactly what I did in my "fork". I believe it is a greate improvements if:

1. The definitions of the architectures are performed in individiual classes (and then have imports only required for this style of arch). By doing this and having the "jmolecules-core" modules set as provided in this module, you can focus on aspects that you need only.

2. The definitions (of layered) architectures by default use the `IsLayerType` but allow (using and additional builder method) to set additional Marker classes.

Do you want me to support this work somehow?

Cheers,

Simon
