### ISSUE TITLE
Generate JPA mappings for list of value objects

### ISSUE THREAD

**Issue by seekM** [xmolecules/jmolecules-integrations#201]
Hello, thanks a lot for this project!

As it is stated in jmolecules-bytebuddy's readme, JPA annotations are generated for `AggregateRoot` and `Entity`. 

I experimented a bit and persisting a `ValueObject` being a field within an `AggregateRoot` worked for me as well. I looked a bit at the source code and it seems to me that `@Embeddable` is generated for `ValueObject` in this case.

However, what didn't work for me is to have a list of `ValueObject`s within an `Aggregate Root`. To make it I work in this case, I had to manually annotate the respective field with the `@OneToMany` annotation and use `@Entity`, `@Id` and `@GeneratedValue` for the `ValueObject`. This worked on it's own, however, I ran into problems when the `AggregateRoot` both had a field of `ValueObject` and a field of a list the same `ValueObject` type (I haven't looked into this further yet though).

Would it be possible to add support for generating JPA annotations for a list of ValueObjects as well?

**Comment by odrotbohm** [comment]
I think simply manually annotating the `List<YourValueObject` with `@ElementCollection` is what JPA would require here. I think we could generate those.

**Comment by seekM** [comment]
I tested it and it works. Thanks!
