### ISSUE TITLE
jmolecules-apt incompatible with kmolecules-ddd annotations

### ISSUE THREAD

**Issue by BWohlbrecht** [xmolecules/jmolecules-integrations#247]
I noticed that jmolecules-apt only considers annotations from jmolecules-ddd and is not compatible with the equivalent annotations from kmolecules-ddd.

In fact a simple test with jmolecules-apt and kmolecules-ddd annotations will result in StackOverflowExceptions on build:
https://github.com/BWohlbrecht/jmolecules-apt-kotlin

Since jmolecules-ddd and kmolecules-ddd use the same package namespace, it seems it won't be possible to properly support both in jmolecules-apt.

Are there any plans for a Kotlin equivalent (kmolecules-apt)?

**Comment by odrotbohm** [comment]
This is caused by Kotlin annotations some times self-referencing each other. I can exclude processing those entirely.
