### ISSUE TITLE
ArchUnit verification fails for annotated aggregate references as collection elements

### ISSUE THREAD

**Issue by etrandafir93** [xmolecules/jmolecules-integrations#253]
When it comes to validating the annotated classes, _JMoleculesDddRules_ fails to catch the violation for an aggregate referencing a Collection of other aggregates as shown below: 

```java
@AggregateRoot 
class AnnotatedAggregate { ... }

@AggregateRoot
class OtherAnnotatedAggregate {
    AnnotatedAggregate invalidAnnotatedAggregate; // <-- throws violation (correct)
    Collection<AnnotatedAggregate> invalidAnnotatedAggregateInCollection; // <-- doesn't throw violation (not correct)
}
```

Reproduced in tests, [here](https://github.com/etrandafir93/jmolecules-integrations/commit/12ebe3aed718348a36acec4c8555250c4320392e).

PS: this works ok for the interfaces, and only fails with the annotations. Also, I believe it can be interesting to have that same test/assertions run against two set of objects (one using the interfaces and its equivalent that uses annotations).

If the project is open for contributions, I wouldn't mind looking into it. 

---

Later edit: This rule also seems to be skipped when it comes to annotated objects: _Aggregates only refer to entities that are declared to be part of it_.

Example here:
```java

@AggregateRoot
static class SomeAnnotatedAggregate {
    // ...
    AnnotatedEntity valid;
}

@AggregateRoot
static class OtherAnnotatedAggregate {
    AnnotatedEntity invalidAnnotatedEntity; // <-- doesn't throw violation (not correct)
    Collection<AnnotatedEntity> invalidAnnoatedEntityInCollection; // <-- doesn't throw violation (not correct)
}
```

I have added these failing test cases to my branch and created PR (#254) for visibility:  
https://github.com/xmolecules/jmolecules-integrations/pull/254

**Comment by odrotbohm** [comment]
I've applied the addition for the collection element verification. For the entity verification, please refer to my comment on the PR.
