### ISSUE TITLE
test that identies are only represented with "custom identity value objects" e.g Identifier are used.

### ISSUE THREAD

**Issue by xenoterracide** [xmolecules/jmolecules-integrations#261]
On page 177 of Implementing Domain Driven Design it suggests that one should use a custom identity Value object. E.g. `ProductId` instead of `String`, `Long` or `UUID`.

**Comment by odrotbohm** [comment]
That's already in place in the definition of `AggregateRoot<T extends AggregateRoot<T, ID>, ID extends Identifier>`. As aggregates are the primary abstractions to refer to, we decided to only enforce this through the compiler on the aggregate level and not for entities. Custom ArchUnit rules would be the way to go if you want to extend on this.
