### ISSUE TITLE
ArchUnit integration strongly depends on all jMolecules architecture artifacts

### ISSUE THREAD

**Issue by eliezio** [xmolecules/jmolecules-integrations#271]
Hi @odrotbohm 

![Image](https://github.com/user-attachments/assets/74ba2fff-5b70-4edf-b489-8c8fd324c389)

After [this commit](https://github.com/xmolecules/jmolecules-integrations/commit/281bf026254812d7d2018ee13e0a5b8d54bd48d7) the `jmolecules-{layered,onion,hexagonal}-architecture` modules are now mandatory runtime dependencies of the `archunit` module. Was this intentional?

**Comment by odrotbohm** [comment]
Nope. I'll issue a bugfix release tomorrow.

**Comment by odrotbohm** [comment]
I spoke to soon.
