### ISSUE TITLE
Hexagonal Architecture tests are failing

### ISSUE THREAD

**Issue by sfgvieira** [xmolecules/jmolecules-integrations#278]
On version **0.21.0** all tests in **JMoleculesHexagonalRulesTest.java** pass, however if you upgrade to any of the newer versions they fail.

![Image](https://github.com/user-attachments/assets/a1b76f2d-2c88-437b-97fa-4bb89c4bcf3d)

**Comment by odrotbohm** [comment]
Any chance you provide a reproducer? You don't seem to use the jMolecules ArchUnit verifications?

**Comment by sfgvieira** [comment]
Hi @odrotbohm,
Just run (manually, with IntelliJ for example) the tests on `jmolecules-archunit/src/test/java/org/jmolecules/archunit/JMoleculesHexagonalRulesTest.java` from master or any tag after 0.21.0 and you will see it failing.
If I do a `mvn clean install` I see that these tests are not executed.

**Comment by odrotbohm** [comment]
I'm still investigating why the nested test classes don't get executed during a build. That said, I've pushed a fix for the actual verification. Note that full detection of meta-annotations (`@Port`, `@Adapter`) will require an upgrade to jMolecules 1.10 (currently only available in snapshots). If you stick to the concrete ones, you should be good on the currently compiled against 1.8.

Would you mind giving the snapshots a try?
