### ISSUE TITLE
Link to  ByteBuddy JPA example broken (Docs)

### ISSUE THREAD

**Issue by bertilmuth** [xmolecules/jmolecules-integrations#69]
The link to the ByteBuddy example points to this location, which no longer exists:
https://github.com/xmolecules/jmolecules-integrations/blob/main/jmolecules-examples/jmolecules-spring-data-jpa

Instead, it should probably point to this location:
https://github.com/xmolecules/jmolecules-examples/tree/main/jmolecules-spring-data-jpa

**Comment by odrotbohm** [comment]
Thanks for reporting this. Should be fixed now!

**Comment by bertilmuth** [comment]
Looks good.
